"""add_exercise_and_exercise_submission_tables

Revision ID: c3499087d8f4
Revises: 7b0c4802b509
Create Date: 2025-11-22 19:27:42.440006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3499087d8f4'
down_revision: Union[str, None] = '7b0c4802b509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content_id', sa.String(), nullable=False),
    sa.Column('form_id', sa.String(length=255), nullable=False),
    sa.Column('embed_code', sa.Text(), nullable=False),
    sa.Column('form_title', sa.String(length=255), nullable=False),
    sa.Column('allow_multiple_submissions', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_content_id'), 'exercises', ['content_id'], unique=True)
    op.create_index(op.f('ix_exercises_form_id'), 'exercises', ['form_id'], unique=False)
    op.create_table('exercise_submissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('exercise_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('form_submission_id', sa.String(length=255), nullable=False),
    sa.Column('submission_data', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('webhook_received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exercise_id', name='uq_user_exercise_submission')
    )
    op.create_index(op.f('ix_exercise_submissions_exercise_id'), 'exercise_submissions', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercise_submissions_user_id'), 'exercise_submissions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_submissions_user_id'), table_name='exercise_submissions')
    op.drop_index(op.f('ix_exercise_submissions_exercise_id'), table_name='exercise_submissions')
    op.drop_table('exercise_submissions')
    op.drop_index(op.f('ix_exercises_form_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_content_id'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
